name: Teste Automático

on:
  schedule:
    # 15:30 no Brasil (Brasília) = 18:30 UTC
    - cron: '40 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependências
        run: |
          pip install pandas selenium gspread oauth2client pytz streamlit

      - name: Executar script de envio
        env:
          EMAIL_CORP: ${{ secrets.EMAIL_CORP }}
          SENHA_SISTEMA: ${{ secrets.SENHA_SISTEMA }}
          SENHA_ZULIP: ${{ secrets.SENHA_ZULIP }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
          GOOGLE_JSON_CREDENTIALS: ${{ secrets.GOOGLE_JSON_CREDENTIALS }}
        run: python bot_scheduler.py
